import { ai, db, error, json, router, secrets, storage } from '@appdeploy/sdk';
import pdfParse from 'pdf-parse';
import * as XLSX from 'xlsx';
import mammoth from 'mammoth';
import { createClerkClient, verifyToken } from '@clerk/backend';
import { createHmac, randomUUID, timingSafeEqual } from 'node:crypto';

type User={id:string;name:string;email:string;workspaceId:string;currency?:string};
type Customer={id:string;workspaceId:string;name:string;email:string;status:string;value:number;initials:string};
type Conversation={id:string;workspaceId:string;customer:string;channel:string;title:string;preview:string;time:string;priority:string;insight:string;action:string;content:string};
type Transaction={id:string;workspaceId:string;type:'income'|'expense';label:string;amount:number;date:string};
async function clerkConfig(){const publishableKey=await secrets.readSecret('CLERK_PUBLISHABLE_KEY');const secretKey=await secrets.readSecret('CLERK_SECRET_KEY');return {publishableKey,secretKey};}
async function currentUser(body:any){const token=String(body?.clerkToken||'').trim();if(!token)return null;try{const {secretKey}=await clerkConfig();const clerk=createClerkClient({secretKey});const claims=await verifyToken(token,{secretKey});const clerkId=String(claims.sub||'');if(!clerkId)return null;const cu=await clerk.users.getUser(clerkId);const name=cu.fullName||[cu.firstName,cu.lastName].filter(Boolean).join(' ')||'SignalDesk user';const email=cu.primaryEmailAddress?.emailAddress||'';const r=await db.list<User>('users',{limit:100});let u=r.items.find(x=>x.id===clerkId);if(!u){const workspaceId='ws_'+randomUUID();const [id]=await db.add('users',[{id:clerkId,name,email,workspaceId,currency:'USD'}]);u={id:String(id||clerkId),name,email,workspaceId,currency:'USD'};}else if(u.name!==name||u.email!==email){await db.update('users',u.id,{name,email});u={...u,name,email};}return u;}catch{return null;}}
async function ws<T extends Record<string,unknown>>(table:string,id:string){const r=await db.list<T>(table,{limit:100});return r.items.filter(x=>x.workspaceId===id)}
function fallback(content:string){const clean=content.replace(/\s+/g,' ').trim();const preview=clean.length>110?clean.slice(0,107)+'...':clean;const hot=/buy|budget|ready|proposal|price|contract|renew/i.test(clean);return {customer:'Captured signal',channel:'Captured note',title:hot?'High-intent follow-up':'Business signal',preview,time:'Just now',priority:hot?'High':'Medium',insight:hot?'The context contains a clear commercial signal. Move the conversation toward a concrete next step.':'There is useful context here. Convert it into one explicit action before it gets lost.',action:hot?'Respond with a concrete next step':'Create one follow-up action'}}
async function openRouterChat(messages:{role:'system'|'user'|'assistant';content:string}[],maxTokens=420){const key=await secrets.readSecret('OPENROUTER_API_KEY');const response=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json','HTTP-Referer':'https://signaldesk-fadaz6.v2.appdeploy.ai/','X-OpenRouter-Title':'SignalDesk'},body:JSON.stringify({models:['~openai/gpt-latest','~anthropic/claude-sonnet-latest'],provider:{allow_fallbacks:true},messages,max_tokens:maxTokens,temperature:.55})});if(!response.ok)throw new Error(`OpenRouter request failed: ${response.status}`);const data:any=await response.json();const text=String(data?.choices?.[0]?.message?.content||'').trim();if(!text)throw new Error('OpenRouter returned no answer');return {text,model:String(data?.model||'OpenRouter model')}}
function mentorFallback(question:string){const q=question.toLowerCase();if(/price|pricing|charge|cost/.test(q))return 'Start with a clear value-based offer: define the outcome, the customer it is for, what is included, and one simple price. Test the message with real prospects before adding more tiers.';if(/sales|sell|close|lead|prospect/.test(q))return 'Focus the sales loop on one customer segment, one painful problem, and one next step. Review your recent conversations, identify the strongest buying signal, and follow up with a specific outcome rather than a generic check-in.';if(/market|marketing|content|social/.test(q))return 'Choose one audience and one repeatable channel. Publish useful proof around the problem you solve, then measure conversations and qualified leads rather than chasing reach alone.';if(/customer|retention|churn|support/.test(q))return 'Start with the customer signal: what happened, why it matters, and what should happen next. Turn repeated questions into reusable answers and follow up on unresolved issues quickly.';return 'Break the question into three parts: the business goal, the evidence you already have, and the next action you can test this week. If you share the situation, I can help you work through it step by step.'}
async function understand(content:string){try{const r=await ai.generate({system:'You are SignalDesk. Turn business context into concise JSON. Never invent facts; if a name is absent, use Captured signal.',prompt:content,schema:{type:'object',properties:{customer:{type:'string'},channel:{type:'string'},title:{type:'string'},preview:{type:'string'},priority:{type:'string'},insight:{type:'string'},action:{type:'string'}},required:['customer','channel','title','preview','priority','insight','action']},maxTokens:400,thinkingMode:'FAST'});return JSON.parse(r.text)}catch{try{const r=await openRouterChat([{role:'system',content:'Turn the supplied business context into JSON with customer, channel, title, preview, priority, insight, and action. Never invent facts. If a name is absent, use Captured signal. Return JSON only.'},{role:'user',content}],400);return JSON.parse(r.text)}catch{return fallback(content)}}}

function decodeBase64(value:string){const raw=value.includes(',')?value.split(',').pop()!:value;return Buffer.from(raw,'base64')}
function webhookRawBody(event:any,body:any){const raw=event?.body;if(typeof raw==='string'&&raw)return event?.isBase64Encoded?Buffer.from(raw,'base64').toString('utf8'):raw;return JSON.stringify(body??{});} async function verifyPaddleWebhook(event:any,body:any){const signature=String(event?.headers?.['paddle-signature']||event?.headers?.['Paddle-Signature']||'');if(!signature)return {ok:false,status:400,message:'Paddle-Signature is required'};let secret='';try{secret=await secrets.readSecret('PADDLE_WEBHOOK_SECRET')}catch{return {ok:false,status:500,message:'Paddle webhook secret is not configured'}}const parts=Object.fromEntries(signature.split(';').map((part:string)=>{const [k,...v]=part.split('=');return [k,v.join('=')]}));const timestamp=String(parts.ts||'');const signatures=signature.split(';').filter((part:string)=>part.startsWith('h1=')).map((part:string)=>part.slice(3)).filter(Boolean);const ts=Number(timestamp);if(!timestamp||!Number.isFinite(ts))return {ok:false,status:400,message:'Invalid Paddle signature timestamp'};if(Math.abs(Date.now()-ts*1000)>5000)return {ok:false,status:408,message:'Paddle webhook event expired'};const raw=webhookRawBody(event,body);const expected=createHmac('sha256',secret).update(`${timestamp}:${raw}`,'utf8').digest('hex');const valid=signatures.some((candidate:string)=>candidate.length===expected.length&&timingSafeEqual(Buffer.from(candidate),Buffer.from(expected)));if(!valid)return {ok:false,status:401,message:'Invalid Paddle signature'};return {ok:true,raw};} async function convertFile(fileName:string,mime:string,data:string){const buffer=decodeBase64(data);if(buffer.length>12*1024*1024)throw new Error('File is too large. Please keep uploads under 12 MB.');const lower=fileName.toLowerCase();if(lower.endsWith('.pdf')||mime==='application/pdf'){const r=await pdfParse(buffer);return r.text.trim()}if(lower.endsWith('.docx')||mime==='application/vnd.openxmlformats-officedocument.wordprocessingml.document'){const r=await mammoth.extractRawText({buffer});return r.value.trim()}if(lower.endsWith('.xlsx')||lower.endsWith('.xls')||lower.endsWith('.csv')||mime.includes('spreadsheet')||mime==='text/csv'){const wb=XLSX.read(buffer,{type:'buffer'});return wb.SheetNames.map(name=>'Sheet: '+name+'\\n'+XLSX.utils.sheet_to_csv(wb.Sheets[name])).join('\\n\\n').trim()}if(lower.endsWith('.txt')||lower.endsWith('.md')||mime.startsWith('text/'))return buffer.toString('utf8').trim();throw new Error('Unsupported file type. Use PDF, TXT, CSV, XLS, XLSX, DOCX or Markdown.')}
export const handler=router({
 'POST /api/auth/config':[async()=>{try{const {publishableKey}=await clerkConfig();return json({publishableKey})}catch{return json({publishableKey:''})}}],
 'POST /api/auth/signup':[async()=>error('Authentication is managed by Clerk. Please use the SignalDesk sign-up screen.',410)],
 'POST /api/auth/login':[async()=>error('Authentication is managed by Clerk. Please use the SignalDesk sign-in screen.',410)],
 'POST /api/auth/logout':[async()=>json({ok:true})],
 'POST /api/workspace':[async({body})=>{const u=await currentUser(body);if(!u)return error('Unauthorized',401);const [customers,conversations,transactions]=await Promise.all([ws<Customer>('customers',u.workspaceId),ws<Conversation>('conversations',u.workspaceId),ws<Transaction>('transactions',u.workspaceId)]);return json({user:{id:u.id,name:u.name,email:u.email,workspaceId:u.workspaceId,currency:u.currency||'USD'},customers,conversations,transactions})}],
 'POST /api/profile':[async({body})=>{const u=await currentUser(body);if(!u)return error('Unauthorized',401);const currency=String((body as any).currency||'USD');if(!['USD','LKR','EUR','GBP'].includes(currency))return error('Unsupported currency',400);await db.update('users',u.id,{currency});return json({ok:true,currency})}],
 'POST /api/customers':[async({body})=>{const u=await currentUser(body);if(!u)return error('Unauthorized',401);const b=body as any,name=String(b.name||'').trim();if(!name)return error('Customer name is required',400);const c={workspaceId:u.workspaceId,name,email:String(b.email||''),status:'New',value:0,initials:name.split(/\s+/).slice(0,2).map((x:string)=>x[0]).join('').toUpperCase()};const [id]=await db.add('customers',[c]);return json({customer:{...c,id}})}],
 'POST /api/transactions':[async({body})=>{const u=await currentUser(body);if(!u)return error('Unauthorized',401);const b=body as any,amount=Number(b.amount);if(!Number.isFinite(amount)||amount<=0||!['income','expense'].includes(b.type))return error('Valid amount and type are required',400);const t={workspaceId:u.workspaceId,type:b.type,label:String(b.label||'').trim(),amount,date:String(b.date||new Date().toISOString().slice(0,10))};if(!t.label)return error('Description is required',400);const [id]=await db.add('transactions',[t]);return json({transaction:{...t,id}})}],
 'POST /api/conversations':[async({body})=>{const u=await currentUser(body);if(!u)return error('Unauthorized',401);const b=body as any;if(!String(b.content||'').trim())return error('Content is required',400);const a=await understand(String(b.content));const record={workspaceId:u.workspaceId,content:String(b.content),...a};const [id]=await db.add('conversations',[record]);return json({conversation:{...record,id}})}],
 'POST /api/files/convert':[async({body})=>{const u=await currentUser(body);if(!u)return error('Unauthorized',401);const b:any=body;const name=String(b.fileName||'').trim();const mime=String(b.mimeType||'application/octet-stream');const data=String(b.data||'');if(!name||!data)return error('File name and data are required',400);try{const text=await convertFile(name,mime,data);if(!text)return error('No readable text was found in this file',422);const path='workspaces/'+u.workspaceId+'/imports/'+randomUUID()+'-'+name.replace(/[^a-zA-Z0-9._-]/g,'_');await storage.write([{path,content:data,contentType:mime}]);return json({fileName:name,text,stored:true})}catch(e:any){return error(e?.message||'Could not convert this file',422)}}],
 'POST /api/billing/config':[async({body})=>{const u=await currentUser(body);if(!u)return error('Unauthorized',401);try{const rawKey=String(await secrets.readSecret('PADDLE_API_KEY')||'').trim().replace(/^Bearer\\s+/i,'').trim();const token=String(await secrets.readSecret('PADDLE_CLIENT_TOKEN')||'').trim().replace(/^Bearer\\s+/i,'').trim();const priceId='pri_01m3pxczzqkv25fj4mhz66kjmb';const productId='pro_01m3px99f58awgx0k8hsd3rd4q';const keySandbox=/^pdl_sdbx_apikey_/.test(rawKey);const keyLive=/^pdl_live_apikey_/.test(rawKey);const tokenSandbox=token.startsWith('test_');const tokenLive=token.startsWith('live_');const environment=keySandbox?'sandbox':keyLive?'live':tokenSandbox?'sandbox':'live';const mismatch=(keySandbox&&tokenLive)||(keyLive&&tokenSandbox);if(mismatch)return json({configured:false,clientToken:'',priceId,productId,environment:keySandbox?'sandbox':keyLive?'live':'unknown',keyEnvironment:keySandbox?'sandbox':keyLive?'live':'unknown',tokenEnvironment:tokenSandbox?'sandbox':tokenLive?'live':'unknown',environmentMismatch:true,code:'PADDLE_ENVIRONMENT_MISMATCH',message:'Paddle API key and client token are for different environments. Use both Sandbox credentials or both Live credentials.'});return json({configured:Boolean(token&&rawKey),clientToken:token,priceId,productId,environment,keyEnvironment:keySandbox?'sandbox':keyLive?'live':'unknown',tokenEnvironment:tokenSandbox?'sandbox':tokenLive?'live':'unknown',environmentMismatch:false})}catch{return json({configured:false,priceId:'pri_01m3pxczzqkv25fj4mhz66kjmb',productId:'pro_01m3px99f58awgx0k8hsd3rd4q'})}}],
 'POST /api/billing/validate':[async({body})=>{const u=await currentUser(body);if(!u)return error('Unauthorized',401);try{const rawKey=String(await secrets.readSecret('PADDLE_API_KEY')||'').trim();const key=rawKey.replace(/^Bearer\s+/i,'').trim();const rawToken=String(await secrets.readSecret('PADDLE_CLIENT_TOKEN')||'').trim();const token=rawToken.replace(/^Bearer\s+/i,'').trim();const priceId='pri_01m3pxczzqkv25fj4mhz66kjmb';if(!key)return json({ok:false,code:'PADDLE_API_KEY_MISSING',message:'Paddle API key is missing'});if(!token)return json({ok:false,code:'PADDLE_CLIENT_TOKEN_MISSING',message:'Paddle client token is missing'});const isSandboxKey=/^pdl_sdbx_apikey_[a-z\d]{26}_[a-zA-Z\d]{22}_[a-zA-Z\d]{3}$/.test(key);const isLiveKey=/^pdl_live_apikey_[a-z\d]{26}_[a-zA-Z\d]{22}_[a-zA-Z\d]{3}$/.test(key);const isLegacyKey=/^[a-z\d]{50}$/.test(key);if(!isSandboxKey&&!isLiveKey&&!isLegacyKey)return json({ok:false,code:'PADDLE_API_KEY_FORMAT_INVALID',message:'Paddle API key format is invalid. Use the API key from Paddle Developer Tools → Authentication.'});const environment=isSandboxKey?'sandbox':isLiveKey?'live':(token.startsWith('test_')?'sandbox':'live');const baseUrl=environment==='sandbox'?'https://sandbox-api.paddle.com':'https://api.paddle.com';const response=await fetch(`${baseUrl}/prices/${priceId}`,{method:'GET',headers:{Authorization:`Bearer ${key}`,'Paddle-Version':'1','Accept':'application/json'}});const raw=await response.text();let data:any={};try{data=JSON.parse(raw)}catch{}if(!response.ok)return json({ok:false,code:String(data?.error?.code||`HTTP_${response.status}`),status:response.status,environment,message:String(data?.error?.detail||data?.error?.code||`Paddle price validation failed (HTTP ${response.status})`)});const price=data?.data;return json({ok:true,environment,priceId:price?.id||priceId,status:price?.status||'active',productId:price?.product_id||''})}catch(e:any){return json({ok:false,code:'PADDLE_VALIDATION_ERROR',message:e?.message||'Could not validate Paddle configuration'})}}],
 'POST /api/billing/status':[async({body})=>{const u=await currentUser(body);if(!u)return error('Unauthorized',401);const r=await db.list<any>('billing_subscriptions',{limit:100});const items=r.items.filter((x:any)=>x.userId===u.id).sort((a:any,b:any)=>Number(b.updatedAt||0)-Number(a.updatedAt||0));return json({active:Boolean(items[0]&&['active','trialing'].includes(String(items[0].status))),subscription:items[0]||null})}],
 'POST /api/billing/webhook':[async(ctx)=>{const verified=await verifyPaddleWebhook(ctx.event,ctx.body);if(!verified.ok)return error(verified.message,verified.status);try{const payload=JSON.parse(String(verified.raw));const eventId=String(payload?.event_id||payload?.id||'');if(eventId){const existing=await db.list<any>('paddle_events',{limit:100});if(existing.items.some((x:any)=>x.eventId===eventId))return json({ok:true,duplicate:true});await db.add('paddle_events',[{eventId,type:String(payload?.event_type||''),receivedAt:Date.now()}]);}const type=String(payload?.event_type||'');const data=payload?.data||{};if(type.startsWith('subscription.')){const custom=data?.custom_data||{};const userId=String(custom?.signaldesk_user_id||'');const subscriptionId=String(data?.id||'');if(subscriptionId){const existing=await db.list<any>('billing_subscriptions',{limit:100});const prior=existing.items.find((x:any)=>x.subscriptionId===subscriptionId);const record={userId,subscriptionId,status:String(data?.status||'unknown'),customerId:String(data?.customer_id||''),priceId:String(data?.items?.[0]?.price?.id||''),updatedAt:Date.now()};if(prior)await db.update('billing_subscriptions',prior.id,record);else await db.add('billing_subscriptions',[record]);}}return json({ok:true})}catch(e:any){console.error('Paddle webhook processing failed',e?.message||e);return error('Paddle webhook processing failed',500)}}],
  'POST /api/social/review':[async({body})=>{
   const u=await currentUser(body);
   if(!u)return error('Unauthorized',401);
   const url=String((body as any)?.url||'').trim();
   const platform=String((body as any)?.platform||'Social media');
   if(!/^https?:\/\//i.test(url))return error('Enter a valid http or https URL.',400);
   let scraped:any=null;
   try{scraped=await ai.scrape({url})}catch{}
   if(!scraped||scraped.status>=400||!String(scraped.text||'').trim()){
     try{
       const response=await fetch(url,{redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 SignalDesk','Accept':'text/html,application/xhtml+xml,text/plain;q=0.9,*/*;q=0.7'}});
       const raw=await response.text();
       const plain=raw.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
       scraped={status:response.status,title:'',text:plain};
     }catch{
       return json({ok:false,message:'This public page could not be reached from SignalDesk. Check that the URL is public and try again.'});
     }
   }
   if(!scraped||scraped.status>=400)return json({ok:false,message:'The social page could not be read. Try a public profile URL.'});
   const source=String(scraped.text||'').trim();
   if(!source)return json({ok:false,message:'The page is reachable but does not expose readable public content.'});
   const analysisPrompt='Review this public '+platform+' page for a small-business growth workspace. Do not invent facts. Separate observations from suggestions. Return JSON with analysis, strengths, opportunities, nextSteps, contentIdeas, and updates. Only use facts present in the supplied page content. Suggestions can be strategic but must be clearly framed as suggestions. URL: '+url+'\n\nPAGE CONTENT:\n'+source.slice(0,16000);
   try{
     const result=await ai.generate({
       system:'Analyze only the supplied public page content. Never invent followers, engagement, audience demographics, products, offers, posting frequency, or performance. Return JSON only. Keep observations grounded and suggestions actionable.',
       prompt:analysisPrompt,
       schema:{type:'object',properties:{
         analysis:{type:'string'},
         strengths:{type:'array',items:{type:'string'}},
         opportunities:{type:'array',items:{type:'string'}},
         nextSteps:{type:'array',items:{type:'string'}},
         contentIdeas:{type:'array',items:{type:'string'}},
         updates:{type:'array',items:{type:'string'}}
       },required:['analysis','strengths','opportunities','nextSteps','contentIdeas','updates']},
       maxTokens:900,
       thinkingMode:'FAST'
     });
     const parsed=JSON.parse(result.text);
     return json({
       ok:true,
       url,
       title:scraped.title||'',
       status:scraped.status,
       analysis:String(parsed.analysis||''),
       strengths:Array.isArray(parsed.strengths)?parsed.strengths.map(String):[],
       opportunities:Array.isArray(parsed.opportunities)?parsed.opportunities.map(String):[],
       nextSteps:Array.isArray(parsed.nextSteps)?parsed.nextSteps.map(String):[],
       contentIdeas:Array.isArray(parsed.contentIdeas)?parsed.contentIdeas.map(String):[],
       updates:Array.isArray(parsed.updates)?parsed.updates.map(String):[]
     });
   }catch{
     return json({ok:false,message:'The page was read, but AI analysis is temporarily unavailable. Please try again.'});
   }
 }],
 'POST /api/ai/reply':[async({body})=>{const u=await currentUser(body);if(!u)return error('Unauthorized',401);const c=(body as any).conversation;if(!c)return error('Conversation is required',400);try{const r=await ai.generate({system:'Write a concise customer reply. Never invent commitments or facts.',prompt:JSON.stringify(c),maxTokens:300,thinkingMode:'FAST'});return json({reply:r.text,provider:'primary'})}catch{try{const r=await openRouterChat([{role:'system',content:'Write a concise customer reply. Never invent commitments or facts.'},{role:'user',content:JSON.stringify(c)}],300);return json({reply:r.text,provider:'openrouter',model:r.model})}catch{return json({reply:'AI is temporarily unavailable. Review the conversation and write the response manually.',provider:'local-fallback'})}}}] ,
 'POST /api/ai/mentor':[async({body})=>{const u=await currentUser(body);if(!u)return error('Unauthorized',401);const b:any=body;const question=String(b.question||'').trim();if(!question)return error('Question is required',400);const context=b.context||{};const history=Array.isArray(b.history)?b.history.slice(-8):[];const prompt=JSON.stringify({question,history,workspace:context});try{const r=await ai.generate({system:'You are SignalDesk Business Mentor: an AI assistant and trainer for entrepreneurs. Answer the user directly, explain clearly, and give practical steps or examples when useful. You can discuss business strategy, sales, customers, pricing, marketing, operations, growth, and customer-chat situations. Use workspace data only when relevant and never invent facts. If information is missing, say what would help. Keep the answer useful and conversational.',prompt,maxTokens:420,thinkingMode:'FAST'});return json({advice:r.text,provider:'primary'})}catch{try{const messages=[{role:'system' as const,content:'You are SignalDesk Business Mentor: an AI assistant and trainer for entrepreneurs. Answer directly, teach clearly, and give practical next steps. Cover business questions and customer-chat situations. Use only the supplied workspace context; never invent facts. Be concise but satisfying.'},...history.filter((m:any)=>m&&['user','assistant'].includes(m.role)&&typeof m.content==='string'),{role:'user' as const,content:`Workspace context: ${JSON.stringify(context)}\n\nCurrent question: ${question}`}];const r=await openRouterChat(messages,420);return json({advice:r.text,provider:'openrouter',model:r.model})}catch{return json({advice:mentorFallback(question),provider:'local-fallback'})}}}]
});
